/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Kana.h
 #	source generated by 4D Plugin Wizard
 #	Project : Kana
 #	author : miyako
 #	2020/06/01
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_KANA_H
#define PLUGIN_KANA_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"

#if VERSIONWIN
#include <windows.h>
#include <tchar.h>
#include <wtypes.h>
#include <vector>
#include <string>
#include <iostream>
#endif

#pragma mark -

void Convert_kana(PA_PluginParameters params);

#endif /* PLUGIN_KANA_H */
